workspaces:
  - /Users/jeff/projects

rules:
  - pattern: ""
    clone_strategy: full

  - pattern: ".*/deployment_tools"
    clone_strategy: worktree

  - pattern: ".*/grafana(-enterprise)?$"
    clone_strategy: worktree
